package src;

import java.io.BufferedWriter;
import java.io.File;
import java.io.FileWriter;
import java.io.IOException;

public class SPICEcomplier {

    public Circuit<Component> circuit;
    public boolean wireResistance;

    public SPICEcomplier(){
        this(null);
    }
    
    public SPICEcomplier(Circuit<Component> circuit, boolean wireResistance){
        this.circuit        = circuit;
        this.wireResistance = wireResistance;
    }

    public SPICEcomplier(Circuit<Component> circuit){
        this.circuit        = circuit;
        this.wireResistance = false;
    }

    public void createFile(File file, String fileName, int temperature, double timeStart, double timeEnd) throws IOException{
        file.setWritable(true); // while in most cases this is unnecessary, this could fix come up and dose not really hurt speed
        FileWriter fileWriter = new FileWriter(file);
        BufferedWriter bufferedWriter = new BufferedWriter(fileWriter);

        bufferedWriter.write("*" + fileName + "\n"); // the first line of the file should be the file name (this does not need to include a "*" because the first line is always skipped by ngspice)
        bufferedWriter.write("*This netlist was generated by CENI\n");
        bufferedWriter.write("*This netlist will be run at a temperature of " + temperature + "\n.option temp=" + temperature + "\n");
        bufferedWriter.write("*");

        bufferedWriter.close();        
    }

    public String toString(){
        return circuit.toString();
    }
}
